@startuml

interface Interface1{
operation1():void
operation2():void
operation3():void
operation4():void
operation5():void
}
class C
class A
class B
class D
Interface1 <|.. B
Interface1 <|.. D
Interface1 <.. A
Interface1 <.. C
@enduml