@startuml

class Pizza{
prepare():void
bake():void
cut():void
box():void
}

class CheesePizza


class GreekPizza

class OrderPizza

OrderPizza..>CheesePizza
OrderPizza..>GreekPizza
OrderPizza..>Pizza


GreekPizza --|>Pizza
CheesePizza --|>Pizza
@enduml